version: "3.7"

services:
  system-manager:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./code/templates:/opt/nuvlaedge/templates
      - ./code/static:/opt/nuvlaedge/static
      - ./code/test/.nuvlabox-status:/srv/nuvlaedge/shared/.nuvlabox-status
    labels:
      - nuvlaedge.component=True
      - nuvlaedge.deployment=production
      - nuvlabox.component=True
      - nuvlabox.deployment=production
    environment:
      - SKIP_MINIMUM_REQUIREMENTS=False
      - DATA_GATEWAY_NETWORK_ENCRYPTION=True
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3636"]
      interval: 30s
      timeout: 10s
      retries: 4
      start_period: 10s
    ports:
      - 127.0.0.1:3636:3636
