version: "3.7"

services:
  system-manager:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - nuvlaedge.component=True
      - nuvlaedge.deployment=production
      - nuvlabox.component=True
      - nuvlabox.deployment=production
    environment:
      - SKIP_MINIMUM_REQUIREMENTS=False
      - DATA_GATEWAY_NETWORK_ENCRYPTION=True
    restart: on-failure